apiVersion: v1
kind: ConfigMap
metadata:
  name: demoapp-configmap
  namespace: demoapp
data:
  application.properties: |
    spring.data.mongodb.host=mongodb
    spring.data.mongodb.port=27017
    spring.data.mongodb.database=demodb
