{
 "title": "MongoDB Dashboard",
 "tags": [
  "mongodb",
  "database",
  "demoapp"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "MongoDB Connection Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MongoDB Connection Pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "mongodb_driver_pool_size", "legendFormat": "Pool Size" },
    { "expr": "mongodb_driver_pool_checkedout", "legendFormat": "Checked Out" },
    {
     "expr": "mongodb_driver_pool_waitqueuesize",
     "legendFormat": "Wait Queue Size"
    }
   ]
  },
  {
   "title": "MongoDB Query Time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(mongodb_query_time_seconds_sum[5m]) / rate(mongodb_query_time_seconds_count[5m]) * 1000",
     "legendFormat": "MongoDB Query Time (avg)"
    }
   ]
  },
  { "title": "MongoDB Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "MongoDB Read Operations Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_driver_commands_seconds_count{command=~\"find|findOne\"}[5m])",
     "legendFormat": "{{command}} - {{collection}}"
    }
   ]
  },
  {
   "title": "MongoDB Write Operations Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_driver_commands_seconds_count{command=~\"insert|update|delete\"}[5m])",
     "legendFormat": "{{command}} - {{collection}}"
    }
   ]
  },
  {
   "title": "MongoDB Command Execution Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(mongodb_driver_commands_seconds_sum{command=~\"find|findOne|insert|update|delete\"}[5m]) / rate(mongodb_driver_commands_seconds_count{command=~\"find|findOne|insert|update|delete\"}[5m])",
     "legendFormat": "{{command}} - {{collection}}"
    }
   ]
  }
 ]
}